spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/deli_db
    username: postgres
    password: postgres1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none   # Use 'validate' or 'none' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
    cache: false



server:
  port: 8080